### ISSUE TITLE
Selecting with rectangle over mutiple units and buildings selects only one unit

### ISSUE THREAD

**Issue by Szunti** [Andrettin/Wyrmgus#14]
I think it's a regression.

Rectangle:
![wyrmsun-rect](https://cloud.githubusercontent.com/assets/1443881/7914521/d781f3f6-0877-11e5-85b3-e69ef4c217a1.jpg)

Result is only one unit selected:
![wyrmsun-select](https://cloud.githubusercontent.com/assets/1443881/7914532/e23e5be0-0877-11e5-9d76-835bafa0f16c.jpg)

**Comment by Szunti** [comment]
It happens also after selecting a building. The next time if you draw a rectangle over multiple units, only one is selected.

**Comment by Andrettin** [comment]
Yes, I noticed now that this happens if a building was already previously selected (this bug was introduced with the latest fix to something else in the multi-selection). Thanks for reporting this! Fixed in https://github.com/Andrettin/Wyrmgus/commit/80c76abcc669380aaeeed918d80f817d517443a4

**Comment by Szunti** [comment]
Still not good: 

With multiple buildings:
![wyrmsun-select](https://cloud.githubusercontent.com/assets/1443881/7921149/b011f33a-08a3-11e5-88e3-e704429c4059.jpg)

A building is selected:
![wyrmsun-sel](https://cloud.githubusercontent.com/assets/1443881/7921152/b24bcb1c-08a3-11e5-9e3e-40dc497f5fd6.jpg)

**Comment by Andrettin** [comment]
Yes, that's on purpose; buildings of different types can't be selected at the same time because they have different commands.

**Comment by Szunti** [comment]
I mean it should select the Buras.

**Comment by Andrettin** [comment]
Yes, that it should do. But when I test here it selects them correctly.

**Comment by Szunti** [comment]
Maybe it depends on the id of the buildings.

**Comment by Andrettin** [comment]
I managed to reproduce it now. Will look deeper into it...

**Comment by Andrettin** [comment]
Fixed in https://github.com/Andrettin/Wyrmgus/commit/c4a0cb0028dea6be9776dd5f45cf1df35227bbcc
